# In the following example, the manifests declares three top-level nodes - one document node and two container nodes. 
# The structure under the container nodes is not explicitly specified. 
# Instead, nodeSelectors are used to have it resolved at runtime dynamically.
structure:
# Here README.md will be renamed to _index.md
  - source: https://github.com/gardener/gardener/blob/master/docs/README.md
    # "name" means that the folder of "path" will be renamed to "concepts"(which is the same)
  - name: concepts
    nodesSelector:
      path: https://github.com/gardener/gardener/tree/master/docs/concepts
  - name: extensions
    nodesSelector:
    # Here a relative paths in the .md files like "[DNS records](dns.md)" are rewritten as "[DNS records](/extensions/dns)"  
      path: https://github.com/gardener/gardener/blob/master/docs/extensions


# !!! I got the following error: 
# W0607 17:16:13.808252   14963 document_worker.go:170] Document node processing halted: No content assigned to document node images
# !!! Here when using "../blob/master/docs/extensions" or ".../tree/master/docs/extensions" the references from "../docs/extensions" stayed absolute.
# This is a bug

# Here where relatives path are handled and rewritten properly according to the new node hierarchy.

# docforge-docs
# ├── concepts
# │   ├── admission-controller.md
# │   ├── apiserver.md
# ...
# │   ├── scheduler.md
# │   └── seed-admission-controller.md
# ├── extensions
# │   ├── backupbucket.md
# │   ├── backupentry.md
# │   ├── cluster.md
# ...
# │   └── worker.md
# └── _index.md